"""add unique constraints

Revision ID: 7741ec531b06
Revises: a20f847c6cc6
Create Date: 2026-06-19 11:00:56.412720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7741ec531b06'
down_revision: Union[str, Sequence[str], None] = 'a20f847c6cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_fin_stock_period', ['stock_id', 'report_period'], unique=True)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_portfolio_name', ['name'])

    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.create_index('idx_signal_stock_date', ['stock_id', 'signal_date'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.drop_index('idx_signal_stock_date')

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_portfolio_name', type_='unique')

    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_fin_stock_period')

    # ### end Alembic commands ###
