"""add portfolio nav table

Revision ID: 87d450639d02
Revises: 7741ec531b06
Create Date: 2026-06-19 13:49:38.190438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d450639d02'
down_revision: Union[str, Sequence[str], None] = '7741ec531b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_nav',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False, comment='净值日期'),
    sa.Column('total_value', sa.Float(), nullable=False, comment='组合总市值(元)'),
    sa.Column('cash_value', sa.Float(), nullable=True, comment='现金(元)'),
    sa.Column('position_value', sa.Float(), nullable=True, comment='持仓市值(元)'),
    sa.Column('daily_return', sa.Float(), nullable=True, comment='日收益率'),
    sa.Column('cumulative_return', sa.Float(), nullable=True, comment='累计收益率'),
    sa.Column('benchmark_value', sa.Float(), nullable=True, comment='基准市值(元)'),
    sa.Column('benchmark_return', sa.Float(), nullable=True, comment='基准日收益率'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_nav', schema=None) as batch_op:
        batch_op.create_index('idx_nav_portfolio_date', ['portfolio_id', 'nav_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_portfolio_nav_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_nav', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_nav_portfolio_id'))
        batch_op.drop_index('idx_nav_portfolio_date')

    op.drop_table('portfolio_nav')
    # ### end Alembic commands ###
